<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\Readme.md">
        <Link>Readme.md</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\OurCheck.Dto\OurCheck.Dto.csproj" />
      <ProjectReference Include="..\OurCheck.Client.Repository.Abstract\OurCheck.Client.Repository.Abstract.csproj" />
      <ProjectReference Include="..\OurCheck.Client.Repository.API\OurCheck.Client.Repository.API.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="14.1.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Services\" />
    </ItemGroup>

</Project>
